<template>
  <option
    v-for="regionCode in regionCodes"
    v-bind:value="regionCode.id"
    v-bind:key="regionCode.id"
  >
    {{ regionCode.name }}
  </option>
</template>

<script>
export default {
  data() {
    return {
      regionCodes: [
        { id: "AD", name: "アンドラ" },
        { id: "AE", name: "アラブ首長国連邦" },
        { id: "AF", name: "アフガニスタン" },
        { id: "AG", name: "アンティグア バーブーダ" },
        { id: "AL", name: "アルバニア" },
        { id: "AM", name: "アルメニア" },
        { id: "AN", name: "オランダ領アンティル" },
        { id: "AO", name: "アンゴラ" },
        { id: "AQ", name: "南極" },
        { id: "AR", name: "アルゼンチン" },
        { id: "AS", name: "米国領サモア" },
        { id: "AT", name: "オーストリア" },
        { id: "AU", name: "オーストラリア" },
        { id: "AW", name: "アルバ" },
        { id: "AZ", name: "アゼルバイジャン" },
        { id: "BA", name: "ボスニア ヘルツェゴビナ" },
        { id: "BB", name: "バルバドス" },
        { id: "BD", name: "バングラディシュ" },
        { id: "BE", name: "ベルギー" },
        { id: "BF", name: "ブルキナ ファソ" },
        { id: "BG", name: "ブルガリア" },
        { id: "BH", name: "バーレーン" },
        { id: "BI", name: "ブルンジ" },
        { id: "BJ", name: "ベナン" },
        { id: "BM", name: "バミューダ諸島" },
        { id: "BN", name: "ブルネイ ダルサラーム" },
        { id: "BO", name: "ボリビア" },
        { id: "BR", name: "ブラジル" },
        { id: "BS", name: "バハマ" },
        { id: "BT", name: "ブータン" },
        { id: "BV", name: "ブーベ島" },
        { id: "BW", name: "ボツワナ" },
        { id: "BY", name: "べラルーシ" },
        { id: "BZ", name: "ベリーズ" },
        { id: "CA", name: "カナダ" },
        { id: "CC", name: "ココス (キーリング) 諸島" },
        { id: "CD", name: "コンゴ民主共和国" },
        { id: "CF", name: "中央アフリカ共和国" },
        { id: "CG", name: "コンゴ" },
        { id: "CH", name: "スイス" },
        { id: "CI", name: "コートジボアール" },
        { id: "CK", name: "クック諸島" },
        { id: "CL", name: "チリ" },
        { id: "CM", name: "カメルーン" },
        { id: "CN", name: "中国" },
        { id: "CO", name: "コロンビア" },
        { id: "CR", name: "コスタリカ" },
        { id: "CS", name: "セルビア モンテネグロ" },
        { id: "CU", name: "キューバ" },
        { id: "CV", name: "カーボ ベルデ" },
        { id: "CX", name: "クリスマス島" },
        { id: "CY", name: "キプロス" },
        { id: "CZ", name: "チェコ共和国" },
        { id: "DE", name: "ドイツ" },
        { id: "DJ", name: "ジブチ" },
        { id: "DK", name: "デンマーク" },
        { id: "DM", name: "ドミニカ" },
        { id: "DO", name: "ドミニカ共和国" },
        { id: "DZ", name: "アルジェリア" },
        { id: "EC", name: "エクアドル" },
        { id: "EE", name: "エストニア" },
        { id: "EG", name: "エジプト" },
        { id: "EH", name: "西サハラ" },
        { id: "ER", name: "エリトリア" },
        { id: "ES", name: "スペイン" },
        { id: "ET", name: "エチオピア" },
        { id: "FI", name: "フィンランド" },
        { id: "FJ", name: "フィジー" },
        { id: "FK", name: "フォークランド (マルビナス) 諸島" },
        { id: "FM", name: "ミクロネシア連邦" },
        { id: "FO", name: "フェロー諸島" },
        { id: "FR", name: "フランス" },
        { id: "GA", name: "ガボン" },
        { id: "GB", name: "イギリス" },
        { id: "GD", name: "グレナダ" },
        { id: "GE", name: "グルジア" },
        { id: "GF", name: "フランス領ギアナ" },
        { id: "GH", name: "ガーナ" },
        { id: "GI", name: "ジブラルタル" },
        { id: "GL", name: "グリーンランド" },
        { id: "GM", name: "ガンビア" },
        { id: "GN", name: "ギニア" },
        { id: "GP", name: "グアドループ島" },
        { id: "GQ", name: "赤道ギニア" },
        { id: "GR", name: "ギリシャ" },
        { id: "GS", name: "南ジョージア南サンドイッチ諸島" },
        { id: "GT", name: "グアテマラ" },
        { id: "GU", name: "グアム" },
        { id: "GW", name: "ギニアビサウ" },
        { id: "GY", name: "ガイアナ" },
        { id: "HK", name: "香港" },
        { id: "HM", name: "ハード島およびマクドナルド諸島" },
        { id: "HN", name: "ホンジュラス" },
        { id: "HR", name: "クロアチア" },
        { id: "HT", name: "ハイチ" },
        { id: "HU", name: "ハンガリー" },
        { id: "ID", name: "インドネシア" },
        { id: "IE", name: "アイルランド" },
        { id: "IL", name: "イスラエル" },
        { id: "IN", name: "インド" },
        { id: "IO", name: "イギリス領インド洋領域" },
        { id: "IQ", name: "イラク" },
        { id: "IR", name: "イラン イスラム共和国" },
        { id: "IS", name: "アイスランド" },
        { id: "IT", name: "イタリア" },
        { id: "JM", name: "ジャマイカ" },
        { id: "JO", name: "ヨルダン" },
        { id: "JP", name: "日本" },
        { id: "KE", name: "ケニア" },
        { id: "KG", name: "キルギスタン" },
        { id: "KH", name: "カンボジア" },
        { id: "KI", name: "キリバス" },
        { id: "KM", name: "コモロ" },
        { id: "KN", name: "セントクリストファー ネーヴィス" },
        { id: "KP", name: "朝鮮民主主義人民共和国 (北朝鮮）" },
        { id: "KR", name: "大韓民国 (韓国)" },
        { id: "KW", name: "クウェート" },
        { id: "KY", name: "ケイマン諸島" },
        { id: "KZ", name: "カザフスタン" },
        { id: "LA", name: "ラオス人民民主共和国" },
        { id: "LB", name: "レバノン" },
        { id: "LC", name: "セントルシア" },
        { id: "LI", name: "リヒテンシュタイン" },
        { id: "LK", name: "スリランカ" },
        { id: "LR", name: "リベリア" },
        { id: "LS", name: "レソト" },
        { id: "LT", name: "リトアニア" },
        { id: "LU", name: "ルクセンブルク" },
        { id: "LV", name: "ラトビア" },
        { id: "LY", name: "リビア アラブ ジャマーヒリーヤ国" },
        { id: "MA", name: "モロッコ" },
        { id: "MD", name: "モナコ" },
        { id: "MD", name: "モルドバ共和国" },
        { id: "MG", name: "マダガスカル" },
        { id: "MH", name: "マーシャル諸島" },
        { id: "MK", name: "マケドニア旧ユーゴスラビア共和国" },
        { id: "ML", name: "マリ" },
        { id: "MM", name: "ミャンマー" },
        { id: "MN", name: "モンゴル" },
        { id: "MO", name: "マカオ" },
        { id: "MP", name: "北マリアナ諸島" },
        { id: "MQ", name: "マルティニーク" },
        { id: "MR", name: "モーリタニア" },
        { id: "MS", name: "モントセラト" },
        { id: "MT", name: "マルタ" },
        { id: "MU", name: "モーリシャス" },
        { id: "MV", name: "モルディブ" },
        { id: "MW", name: "マラウイ" },
        { id: "MX", name: "メキシコ" },
        { id: "MY", name: "マレーシア" },
        { id: "MZ", name: "モザンビーク" },
        { id: "NA", name: "ナミビア" },
        { id: "NC", name: "ニューカレドニア" },
        { id: "NE", name: "ニジェール" },
        { id: "NF", name: "ノーフォーク島" },
        { id: "NG", name: "ナイジェリア" },
        { id: "NI", name: "ニカラグア" },
        { id: "NL", name: "オランダ" },
        { id: "NO", name: "ノルウェー" },
        { id: "NP", name: "ネパール" },
        { id: "NR", name: "ナウル" },
        { id: "NU", name: "ニウエ" },
        { id: "NZ", name: "ニュージーランド" },
        { id: "OM", name: "オマーン" },
        { id: "PA", name: "パナマ" },
        { id: "PE", name: "ペルー" },
        { id: "PF", name: "フランス領ポリネシア" },
        { id: "PG", name: "パプアニューギニア" },
        { id: "PH", name: "フィリピン" },
        { id: "PK", name: "パキスタン" },
        { id: "PL", name: "ポーランド" },
        { id: "PM", name: "サンピエール ミクロン" },
        { id: "PN", name: "ピトケアン諸島" },
        { id: "PR", name: "プエルトリコ" },
        { id: "PS", name: "パレスチナ自治政府" },
        { id: "PW", name: "パラオ" },
        { id: "PY", name: "パラグアイ" },
        { id: "QA", name: "カタール" },
        { id: "RE", name: "レユニオン島" },
        { id: "RO", name: "ルーマニア" },
        { id: "RU", name: "ロシア連邦" },
        { id: "RW", name: "ルワンダ" },
        { id: "SA", name: "サウジアラビア" },
        { id: "SB", name: "ソロモン諸島" },
        { id: "SC", name: "セーシェル" },
        { id: "SD", name: "スーダン" },
        { id: "SE", name: "スウェーデン" },
        { id: "SG", name: "シンガポール" },
        { id: "SH", name: "セントヘレナ" },
        { id: "SI", name: "スロベニア" },
        { id: "SJ", name: "スバールバル ヤンマイエン諸島" },
        { id: "SK", name: "スロバキア" },
        { id: "SL", name: "シエラレオネ" },
        { id: "SM", name: "サンマリノ" },
        { id: "SN", name: "セネガル" },
        { id: "SO", name: "ソマリア" },
        { id: "SR", name: "スリナム" },
        { id: "ST", name: "サントメ プリンシペ" },
        { id: "SV", name: "エルサルバドル" },
        { id: "SY", name: "シリア アラブ共和国" },
        { id: "SZ", name: "スワジランド" },
        { id: "TC", name: "タークス カイコス諸島" },
        { id: "TD", name: "チャド" },
        { id: "TF", name: "フランス南方領" },
        { id: "TG", name: "トーゴ" },
        { id: "TH", name: "タイ" },
        { id: "TJ", name: "タジキスタン" },
        { id: "TK", name: "トケラウ" },
        { id: "TL", name: "東ティモール" },
        { id: "TM", name: "トルクメニスタン" },
        { id: "TN", name: "チュニジア" },
        { id: "TO", name: "トンガ" },
        { id: "TR", name: "トルコ" },
        { id: "TT", name: "トリニダード トバゴ" },
        { id: "TV", name: "ツバル" },
        { id: "TW", name: "台湾省/中華民国" },
        { id: "TZ", name: "タンザニア連合共和国" },
        { id: "UA", name: "ウクライナ" },
        { id: "UG", name: "ウガンダ" },
        { id: "UM", name: "アメリカ合衆国外諸島" },
        { id: "US", name: "アメリカ" },
        { id: "UY", name: "ウルグアイ" },
        { id: "UZ", name: "ウズベキスタン" },
        { id: "VC", name: "セントビンセントおよびグレナディーン諸島" },
        { id: "VE", name: "ベネズエラ" },
        { id: "VG", name: "イギリス領ヴァージン諸島" },
        { id: "VI", name: "アメリカ領ヴァージン諸島" },
        { id: "VN", name: "ベトナム" },
        { id: "VU", name: "バヌアツ" },
        { id: "WF", name: "ウォリス フツナ諸島" },
        { id: "WS", name: "サモア" },
        { id: "YE", name: "イエメン" },
        { id: "YT", name: "マイヨット" },
        { id: "ZA", name: "南アフリカ" },
        { id: "ZM", name: "ザンビア" },
        { id: "ZW", name: "ジンバブエ" },
      ],
    };
  },
};
</script>